name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - uses: actions/checkout@v3

      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: TheGrinderAC/quote-generator
          huggingface_repo_id: Bidhideb/quote-generator
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: Docker
